2021-09-26 20:36:07,807 INFO    MainThread:345456 [wandb_setup.py:_flush():69] setting env: {}
2021-09-26 20:36:07,807 INFO    MainThread:345456 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-26 20:36:07,807 INFO    MainThread:345456 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets-cleaning-data-V2/wandb/run-20210926_203607-13q5rkxd/logs/debug.log
2021-09-26 20:36:07,807 INFO    MainThread:345456 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets-cleaning-data-V2/wandb/run-20210926_203607-13q5rkxd/logs/debug-internal.log
2021-09-26 20:36:07,807 INFO    MainThread:345456 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f329e5b5710>
2021-09-26 20:36:07,808 INFO    MainThread:345456 [wandb_init.py:init():375] calling init triggers
2021-09-26 20:36:07,808 INFO    MainThread:345456 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-26 20:36:07,808 INFO    MainThread:345456 [wandb_init.py:init():424] starting backend
2021-09-26 20:36:07,808 INFO    MainThread:345456 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-26 20:36:07,871 INFO    MainThread:345456 [backend.py:ensure_launched():135] starting backend process...
2021-09-26 20:36:07,934 INFO    MainThread:345456 [backend.py:ensure_launched():140] started backend process with pid: 354382
2021-09-26 20:36:07,935 INFO    MainThread:345456 [wandb_init.py:init():429] backend started and connected
2021-09-26 20:36:07,991 INFO    MainThread:345456 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-26 20:36:07,993 INFO    MainThread:345456 [wandb_init.py:init():477] updated telemetry
2021-09-26 20:36:07,994 INFO    MainThread:345456 [wandb_init.py:init():500] communicating current version
2021-09-26 20:36:09,288 INFO    MainThread:345456 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-26 20:36:09,288 INFO    MainThread:345456 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-26 20:36:10,315 INFO    MainThread:345456 [wandb_init.py:init():540] starting run threads in backend
2021-09-26 20:36:15,321 INFO    MainThread:345456 [wandb_run.py:_console_start():1601] atexit reg
2021-09-26 20:36:15,321 INFO    MainThread:345456 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-26 20:36:15,321 INFO    MainThread:345456 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-26 20:36:15,323 INFO    MainThread:345456 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-26 20:36:15,323 INFO    MainThread:345456 [wandb_init.py:init():565] run started, returning control to user process
2021-09-26 20:36:16,176 INFO    MainThread:345456 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-26 20:36:16,176 INFO    MainThread:345456 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-26 20:36:19,055 INFO    MainThread:345456 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f33a6904dd0>
2021-09-26 20:36:23,804 INFO    MainThread:345456 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-26 20:36:23,850 INFO    MainThread:345456 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-26 20:36:23,850 INFO    MainThread:345456 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-26 20:36:25,718 INFO    MainThread:345456 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f329e5b5310>
2021-09-26 20:36:25,722 INFO    MainThread:345456 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-26 20:36:25,722 INFO    MainThread:345456 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-26 20:36:25,723 INFO    MainThread:345456 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-26 20:36:27,713 INFO    MainThread:345456 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f32857520d0>
2021-09-26 20:36:27,716 INFO    MainThread:345456 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-26 20:36:27,716 INFO    MainThread:345456 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-26 20:36:27,716 INFO    MainThread:345456 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-26 20:36:29,198 INFO    MainThread:345456 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f33a68edf50>
2021-09-26 20:36:29,205 INFO    MainThread:345456 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-26 20:36:29,211 INFO    MainThread:345456 [wandb_setup.py:_flush():69] setting env: {}
2021-09-26 20:36:29,211 INFO    MainThread:345456 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-26 20:36:29,211 INFO    MainThread:345456 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets-cleaning-data-V2/wandb/run-20210926_203629-250sb9g5/logs/debug.log
2021-09-26 20:36:29,211 INFO    MainThread:345456 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets-cleaning-data-V2/wandb/run-20210926_203629-250sb9g5/logs/debug-internal.log
2021-09-26 20:36:29,212 INFO    MainThread:345456 [wandb_init.py:init():375] calling init triggers
2021-09-26 20:36:29,212 INFO    MainThread:345456 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-26 20:36:29,212 INFO    MainThread:345456 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 13q5rkxd
2021-09-26 20:36:29,213 INFO    MainThread:345456 [wandb_run.py:finish():1271] finishing run ranuga-d/NLP-with-Disaster-Tweets-cleaning-data-V2/13q5rkxd
